title: Tony Ak # your name (or website title) here
logo: "/images/Tony.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Performance improvement professional using data and insights to solve life and business challenges
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/anthonyakhigbe/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-V2VL681329 # your Google Analytics tracking ID here
